initial push
codesupport/website-backend pull request #1
Opened 2019-11-21 23:35 UTC by AtrumAmantus

Basic controller, some initial framework, unit tests, not too much.

2019-11-22 15:22 UTC, LamboCreeper requested changes
See comments. :)

2019-11-22 15:22 UTC, LamboCreeper commented on pom.xml
> +    <name>CodeSupport Api</name>
Nitpicking, but could this be `CodeSupport Website API` or `CodeSupport Website Backend`?

2019-11-22 15:22 UTC, LamboCreeper commented on pom.xml
> +    <description>Demo application showing SpringBoot REST Api and hibernate</description>
Change the description to `The backend for the CodeSupport website.`, this is no longer a demo project. :)

2019-11-22 15:22 UTC, LamboCreeper commented on readme.md
> +###Build the App
This entire markdown file doesn't render correctly. Can you go through and fix that please?

2019-11-22 15:22 UTC, LamboCreeper commented on src/main/java/dev/codesupport/web/api/service/UserService.java
> +        //TODO: What should this return?
We'll come back to this when we implement Firebase Authentication.

2019-11-22 19:13 UTC, LamboCreeper approved these changes
Thanks for making those changes, I'd wait until @Kayomn has reviewed too before merging due to the size of the pull request.

2019-11-24 21:06 UTC, Kayomn commented on .mvn/wrapper/MavenWrapperDownloader.java
> +public class MavenWrapperDownloader {
Class is missing a comment?

Hard to say, there is no style guide yet.

2019-11-24 21:12 UTC, Kayomn commented on .mvn/wrapper/MavenWrapperDownloader.java
> +    public static void main(String args[]) {
Again, missing comment?

What is the goal of this main procedure?

2019-11-24 21:13 UTC, Kayomn commented on .mvn/wrapper/MavenWrapperDownloader.java
> +    private static void downloadFileFromURL(String urlString, File destination) throws Exception {
Another missing comment.

2019-11-24 21:14 UTC, Kayomn commented on .mvn/wrapper/MavenWrapperDownloader.java
> +        rbc = Channels.newChannel(website.openStream());
Could simply be:
```java
ReadableByteChannel rbc = Channels.newChannel(new URL(urlString).openStream());
```

2019-11-24 21:17 UTC, Kayomn commented on mvnw
> +  # TODO classpath?
Unresolved TODO in commit?

2019-11-24 21:21 UTC, Kayomn commented on readme.md
> +### Validations
Missing section?

2019-11-24 21:21 UTC, Kayomn commented on readme.md
> +### Conventions
Missing section?

2019-11-24 21:23 UTC, Kayomn commented on src/main/java/dev/codesupport/web/api/ApiServiceApplication.java
> +public class ApiServiceApplication {
Missing comment?

What does this class do?

2019-11-24 21:23 UTC, Kayomn commented on src/main/java/dev/codesupport/web/api/ApiServiceApplication.java
> +    public static void main(String[] args) {
Missing comment?

What does this procedure do?

2019-11-24 21:24 UTC, Kayomn commented on src/main/java/dev/codesupport/web/api/config/ApplicationConfiguration.java
> +class ApplicationConfiguration {
Missing comment?

What does this class do?

2019-11-24 21:24 UTC, Kayomn commented on src/main/java/dev/codesupport/web/api/ApiServiceApplication.java
> +public class ApiServiceApplication {
Missing protection level?

2019-11-24 21:25 UTC, Kayomn commented on src/main/java/dev/codesupport/web/api/config/ApplicationConfiguration.java
> +class ApplicationConfiguration {
Missing protection level?

2019-11-24 21:26 UTC, Kayomn commented on src/main/java/dev/codesupport/web/api/config/ApplicationConfiguration.java
> +    ApplicationConfiguration(
What is this formatting?

2019-11-24 21:26 UTC, Kayomn commented on src/main/java/dev/codesupport/web/api/config/ApplicationConfiguration.java
> +    ) {
What is this formatting?

2019-11-24 21:26 UTC, Kayomn commented on src/main/java/dev/codesupport/web/api/config/ApplicationConfiguration.java
> +class ApplicationConfiguration {
Why can this not just be a static class?

2019-11-24 21:27 UTC, Kayomn commented on src/main/java/dev/codesupport/web/api/config/ApplicationConfiguration.java
> +    }
Why is a constructor being used for something that could very easily be a static procedure on utility class?

2019-11-24 21:31 UTC, Kayomn commented on src/main/java/dev/codesupport/web/api/controller/UserController.java
> +}
Everything in here is missing comments.

2019-11-24 21:31 UTC, Kayomn commented on src/main/java/dev/codesupport/web/api/controller/UserControllerImpl.java
> +}
Everything in here is missing comments.

2019-11-24 21:35 UTC, Kayomn commented on src/main/java/dev/codesupport/web/api/data/entity/UserEntity.java
> +}
All of this is missing comments.

2019-11-28 14:02 UTC, merged